### ISSUE TITLE
Is there a way to configure wildcards?

### ISSUE THREAD

**Issue by SgtSiff** [patrickpr/trapdirector#16]
Is there a way to use wildcards when configuring the SNMP trap handler?

Two consecutive alarms that are the same have unique IDs so I am unable to create a rule to catch them:

<a href="https://ibb.co/7rYpGMH"><img src="https://i.ibb.co/2cnMjVw/Traps.png" alt="Traps" border="0" /></a>

<a href="https://ibb.co/74CQrJQ"><img src="https://i.ibb.co/ySPpgnp/traps2.png" alt="traps2" border="0" /></a>

Setting up the rule for .1.3.6.1.2.1.33.1.6.2.1.2.107 would only pick up the alarm once. A rule for .1.3.6.1.2.1.33.1.6.2.1.2 doesn't work as the alarms have a unique identifier at the end.

Ideally I would be able to add a rule such as .1.3.6.1.2.1.33.1.6.2.1.2.*

This wouldn't cause conflicts as the alarm is deleted from the alarm table once it has been cleared. So despite the alarms shown above as being .1.3.6.1.2.1.33.1.6.2.1.2.109 and .1.3.6.1.2.1.33.1.6.2.1.2.107 the alarm table would only ever show the most recent alarm.

**Comment by patrickpr** [comment]
Hi,

I see the problem : could you send me the Ups MIB file related to this trap ?

Patrick

**Comment by SgtSiff** [comment]
Hi Patrick

Many thanks for taking a look at this.
[UPS-MIB.zip](https://github.com/patrickpr/trapdirector/files/3756854/UPS-MIB.zip)

I have attached the UPS-MIB file.

http://www.oidview.com/mibs/0/UPS-MIB.html gives a nice overview as well.

**Comment by patrickpr** [comment]
OK, so the upsAlarmId is incrementing and used as an index.
I see two solutions for this : either use a regexp or extract the index.
I will check if - and how - other MIBs use this type of index before choosing which one to implement.

I'm currently working on MIB update but I will work on this after and keep this case updated.

Patrick

**Comment by SgtSiff** [comment]
Patrick

Many thanks for your help. The plug-in works really well despite this.

Joe

**Comment by patrickpr** [comment]
Hi,
I'm still not too sure about the best way to implement this, so I did a quick change that should solve your problem. 
In the trap processing, I added the possibility to use some type of wildcard : 

- '\*' means one number : 
.1.3.6.1.2.1.1.\* 
will match 
.1.3.6.1.2.1.1.5 
but not 
.1.3.6.1.2.1.1.5.5
It can also be used inside and multiple times in an oid (ex : .1.3.6.\*.2.1.1.* )

- '\*\*' mean anything : .1.3.6.\*\*  will match anything starting with .1.3.6.

In details : \* will be changed to regexp [0-9]+ and \*\* to .\*

**How to put this in your rule :** 

- Update your trapdirector from master branch to get the update
- Edit your handler
- In your rule, instead of putting '$1$' put '_OID(.1.3.6.1.2.1.33.1.6.2.1.2.\*)'
The rule should look like this : 
_OID(.1.3.6.1.2.1.33.1.6.2.1.2.\*) = ".1.3.6.1.2.1.33.1.6.2.6"
- Save your handler and check your rule in handler list.
- Rule tester will NOT work

Test it and give me feedbacks.

**Comment by SgtSiff** [comment]
Amazing thank you Patrick, I will test this tonight.

**Comment by patrickpr** [comment]
OK, nice. 
I'll close the issue and next steps in future versions will be : 
1) Extend the regexp to display.
2) Ability to enter this in the GUI.

Patrick
